### ISSUE TITLE
Add support for counter metrics in horizontal DB model

### ISSUE THREAD

**Issue by bsmid** [sematext/sematext-agent-java#21]
At the moment counter metrics are supported with DB source only if vertical DB model is used in query output. In that case first column in each row carries the name of attribute, so Agent is able to compare previous measurement of that attribute with current one and produce delta (which is recorded as value of counter metric).

With horizontal model there are N rows in result set, each row containing N columns (which map to N collected attributes which are source for metrics collection). Gauge/Text metrics can always be collected as-is, but since counter metrics depend on previous measurement, Agent has to somehow uniquely identify each row in order to be able to calculate delta for counter metrics.

**Comment by otisg** [comment]
Anything else we need to do here or can we close this?

**Comment by bsmid** [comment]
Nothing, forgot to close.
