### ISSUE TITLE
Implement PostgreSQL monitoring

### ISSUE THREAD

**Issue by otisg** [sematext/sematext-agent-java#8]
First need to identify top NN PG metrics to monitor
PG keeps metrics/stats in various stats tables, so PG metrics can be fetched from there using the JDBC support provided by this agent (see MySQL monitoring configs for examples)

**Comment by otisg** [comment]
Anything left here @nmtien & @bsmid ?

**Comment by bsmid** [comment]
I @nmtien tested the latest version of integration configs, nothing is left.
